# Meta Data for SEO

## Homepage
title = "OSCP Doks"
titleSeparator = "-"
titleAddition = "OSCP Doks is Tyler Butler's personal repository for notes in preparation for the OSCP exam."
description = "OSCP Doks is Tyler Butler's personal repository for notes in preparation for the OSCP exam. The doks additionally cover eJPT and eWPT"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "tbutler0x90"
twitterCreator = "tbutler0x90"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/tbutler0x90"
schemaLinkedIn = "https://www.linkedin.com/in/tyler-b-a700a1aa/"
schemaGitHub = "https://github.com/tcbutler320"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Maintained by <a href=\"https://tbutler.org\">Tyler Butler</a> and Powered by<a href=\"https://getdoks.org/\"> Doks</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
