name = "OSCP Prep"
license = "MIT"
licenselink = "https://github.com/h-enk/doks/blob/master/LICENSE"
description = "OSCP Doks is Tyler Butler's personal repository for notes in preparation for the OSCP exam.""
homepage = "https://getdoks.org/"
tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]
min_version = "0.75.0"

[author]
  name = "Tyler Butler"
  homepage = "https://tbutler.org/"
